on:
   push:
      branches: ['main']

jobs:
   infrastructure:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Set up node
           uses: actions/setup-node@v2
           with:
              node-version: '16'

         - name: Restore node_modules
           id: cache-node-modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: node-modules-static_cdk${{ hashFiles('package.json') }}

         - name: Install
           run: npm install

         - name: Lint
          run: npm run lint

         - name: Test
           run: npm run test
